### ISSUE TITLE
config cache_file_path always set to true

### ISSUE THREAD

**Issue by ryanbjones** [mxenabled/firebolt#8]
https://github.com/mxenabled/firebolt/blob/3439978d7688d728f53358d175b9ea57a48017d9/lib/firebolt/railtie.rb#L10

Notice that the setter makes the above action true
https://github.com/mxenabled/firebolt/blob/3439978d7688d728f53358d175b9ea57a48017d9/lib/firebolt/config.rb#L60-L65

**Comment by liveh2o** [comment]
This is by design. If the path is set, the file warmer should be enabled. Because we process the passed in configs after this, both the path and whether the warmer is enabled can be changed.
